name: dietician-ai
services:
 web_app:
   container_name: dietician_web_app
   build: 
     context: .
     dockerfile: Dockerfile
   ports:
     - "5000:5000"
   volumes:
     - dietician-app-data:/var/lib/python/data
     
 db:
   container_name: dietician_postgres
   image: postgres:latest
   restart: always
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: secret
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - ./db-init-scripts/:/docker-entrypoint-initdb.d/

 pgadmin:
   container_name: dietician_pgadmin
   image: dpage/pgadmin4:latest
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - dietician-pgadmin-data:/var/lib/pgadmin
volumes:
 dietician-db-data:
 dietician-pgadmin-data:
 dietician-app-data: