name: nextjs-blog
services:
 nextjs_web_app:
   build: 
     context: .
     dockerfile: Dockerfile
   ports:
     - "5000:5000"
   volumes:
     - ./entry-scripts/:/usr/local/bin/

volumes:
 blog-data: