name: dietician-AI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Approval
        uses: actions/github-script@v7
        with:
            script: |
              const { owner, repo } = context.repo;
              const { number } = context.issue;
              await github.checks.create({
                owner,
                repo,
                name: 'Approval',
                head_sha: github.context.sha,
                status: 'in_progress',
                output: {
                  title: 'Approval required',
                  summary: 'This deployment requires manual approval.',
                  text: `To approve the deployment, go to the "Checks" tab in this PR, find the "Approval" check, click on "Details", and finally click on "Approve".`
                },
                actions: [{
                  label: 'Approve',
                  description: 'Approve the deployment',
                  identifier: 'APPROVE'
                }]
              });


      - name: Deploy
        run: echo "Deployment is approved and can proceed."
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dietician-ai